const APP_ROUTE = {
    MAIN_TAB: 'MAIN_TAB',
};
const AUTHENTICATE_ROUTE = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    FOGOT_PASSWORD: 'FOGOT_PASSWORD',
};
const HOME_ROUTE = {
    ROOT: 'HOME_ROOT',
    HOME: 'HOME',
    VIDE0_ROUTE: 'VIDE0_ROUTE',
    IMAGE_ROUTE: 'IMAGE_ROUTE',
    VIDE0_LIST: 'VIDE0_LIST',
};
const CONTRACT_ROUTE = {
    ROOT: 'CONTRACT_ROUTE',
    CONTRACT: 'CONTRACT',
};
const PRODUCT_ROUTE = {
    ROOT: 'PRODUCT_ROUTE',
    PRODUCT: 'PRODUCT',
};
const SYSTEM_ROUTE = {
    ROOT: 'SYSTEM_ROUTE',
    SYSTEM: 'SYSTEM',
    PERSONAL_REVENUE: 'PERSONAL_REVENUE',
    SYSTEM_REVENUE: 'SYSTEM_REVENUE',
    DOWNLINE_AGENT: 'DOWNLINE_AGENT',
    ADD_AGENT: 'ADD_AGENT',
};
const ACCOUNT_ROUTE = {
    ROOT: 'ACCOUNT_ROUTE',
    ACCOUNT: 'ACCOUNT',
};
const TAB_NAVIGATION_ROOT = {
    HOME_ROUTE,
    CONTRACT_ROUTE,
    PRODUCT_ROUTE,
    SYSTEM_ROUTE,
    AUTHENTICATE_ROUTE,
    ACCOUNT_ROUTE,
    APP_ROUTE,
};
export {
    AUTHENTICATE_ROUTE,
    TAB_NAVIGATION_ROOT,
    HOME_ROUTE,
    CONTRACT_ROUTE,
    PRODUCT_ROUTE,
    SYSTEM_ROUTE,
    ACCOUNT_ROUTE,
    APP_ROUTE,
};
