const APP_ROUTE = {
    MAIN_TAB: 'MAIN_TAB',
};
const HOME_ROUTE = {
    ROOT: 'HOME_ROOT',
    HOME: 'HOME',
};
const CONTRACT_ROUTE = {
    ROOT: 'CONTRACT_ROUTE',
    CONTRACT: 'CONTRACT',
};
const PRODUCT_ROUTE = {
    ROOT: 'PRODUCT_ROUTE',
    PRODUCT: 'PRODUCT',
};
const SYSTEM_ROUTE = {
    ROOT: 'SYSTEM_ROUTE',
    SYSTEM: 'SYSTEM',
    PERSONAL_REVENUE: 'PERSONAL_REVENUE',
};
const ACCOUNT_ROUTE = {
    ROOT: 'ACCOUNT_ROUTE',
    ACCOUNT: 'ACCOUNT',
};
const TAB_NAVIGATION_ROOT = {
    HOME_ROUTE,
    CONTRACT_ROUTE,
    PRODUCT_ROUTE,
    SYSTEM_ROUTE,
    ACCOUNT_ROUTE,
};
export { TAB_NAVIGATION_ROOT, HOME_ROUTE, CONTRACT_ROUTE, PRODUCT_ROUTE, SYSTEM_ROUTE, ACCOUNT_ROUTE, APP_ROUTE };
